spring:
  application:
    name: order-service
server:
  port: 19092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

management:
#  endpoints:
#    web:
#      exposure:
#        include: prometheus, refresh
#        #prometheust : 애플리케이션의 메트릭(metrics) 정보를 Prometheus가 수집할 수 있는 형식으로 노출 (모니터링)
#        #refresh : 런타임에 애플리케이션의 설정을 다시 로드, Config Server에서 설정이 변경되었을 때 애플리케이션을 재시작하지 않고 변경사항 적용 가능 (설정관리)
#  prometheus:
#    metrics:
#      export:
#        enabled: true
  zipkin: #분산 추적의 시각화를 위한 zipkin 설정
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0